vertex_ai:
  project_location: "us-central1"
  model_name: "gemini-1.5-pro"
  credentials_file: "credential.json"

processing:
  max_workers: 1
  output_file: "results/output.txt"
  dataset_path: "dataset/third.txt"

logging:
  log_dir: "logs"
  level: "INFO"

prompts:
  transaction_template: |
    請根據以下刷卡資料進行分析。資料可能包含以下特性：
    1. 含有亂碼或訂單編號
    2. 關鍵字沒有用分隔符號而黏在一起
    3. 品牌名稱可能混合英文與數字
    4. 可能包含在地小店、工作室等較小型商家
    5. 可能包含連續型消費（如：悠遊加值、街口支付等）
    6. 可能包含外國商家名稱與訂單
    7. 可能包含訂閱服務（如：串流平台）
    8. 商家名稱可能包含特殊符號（如：＊、？、－等）
    請你按照以下步驟處理資料：
    1. 對於沒有分隔的文字，拆分成有意義的關鍵字
    2. 從這些關鍵字中找出商家名稱、付款方式、運送商、通路以及金額
    3. 將找到的名稱轉換成對應的中文名稱
    4. 對於小型商家，即使沒有完整的公司資訊，只要能從名稱辨識出是商家，也請直接列出其商家名稱
    5. 若商家名稱包含分店資訊（如：第X號店、XX分店、XX店等），請只列出主要商家名稱
    6. 只有在完全無法辨識是任何形式的商家時，才回覆「找不到對應名字」並且在後面標注原本名稱
    7. 對於連續型消費（如：悠遊加值），需要統一歸類為該支付方式
    8. 對於外國商家，若為連鎖品牌需轉換為對應中文名稱，若為當地商家則保留原文
    9. 對於平台型消費（如：網購），需分別標注出通路與商家
    10. 將連鎖店的不同分店（如：路易莎各分店）都統一為同一品牌名稱
    輸出格式說明：
    1. 請以且只以下面的格式回覆（所有欄位都必須存在，但若無相關資訊可填寫 None）： 付款方式: XXX; 運送商: None; 金額: XXX; 通路: None; 商家名稱: XXX
    2. 付款方式包含但不限於：悠遊卡、街口支付、全盈支付、TapPay、綠界等
    3. 通路包含但不限於：91APP、蝦皮、博客來等電商平台
    4. 對於訂閱服務（如 Disney+），商家名稱欄位填寫平台名稱
    5. 對於純支付紀錄（如單純的悠遊卡加值），商家名稱欄位填寫 None
    特殊案例處理規則：
    1. 若發現重複紀錄（如：台鐵/台灣鐵路管理局），應統一使用其正式名稱
    2. 對於複合式消費（如：優食-XXX），需分別標注出通路（優食）與商家名稱
    3. 對於包含訂單編號的紀錄（如：FACEBK *H4T3BYK9S2），應去除訂單編號部分
    4. 對於純數字或無法辨識用途的代碼，標注為「找不到對應名字」
    5. 對於外國在地商家（如：當地餐廳），保留其原始名稱
    6. 對於包含商品名稱的消費紀錄，優先使用商家名稱而非商品名稱
    7. 若同時出現英文名稱和中文譯名，優先使用中文譯名

    資料如下：
    {}
